### ISSUE TITLE
New Feature Please :)

### ISSUE THREAD

**Issue by iexcel4u** [twistedatrocity/SWGAide-NGE#11]
There are a few SWG server projects that wish not to be connected to GH or SWGCraft.  I love your application and would love to keep using it in a mode that allows me to manually enter resource data without a server affiliation or connection.  Super Please :)

**Comment by twistedatrocity** [comment]
It loads all of the schematics and any "in spawn" resources from swgcraft.org ... that's how it was originally written and how it currently is. To change that would mean a complete rewrite and/or using some other server to house the data. Understand your desire for this but it just would not be possible right now unless swgcraft was retired and I had to make a new site for the remote data.

In the interim however you could use the inventory feature to store your own resources, as it does allow creating your own resource within inventory with it's own stats.
