### ISSUE TITLE
Bug with resource not being listed although current on SWGCraft.

### ISSUE THREAD

**Issue by Milikilawat** [twistedatrocity/SWGAide-NGE#14]
![Goitzisoc_Avian_Bone](https://user-images.githubusercontent.com/51215336/58668008-8b94d800-832f-11e9-9693-220c16550a1c.png)

The current Rori Avian Bone is not showing in my SWGAide's Current Resources. I checked and it is listed on SWGCraft.org as available atm. I'm not sure if someone marked it as despawned as it showed up on the Depleted tab but I got an error message when I tried to "revive" it - most probably because it was already live again on SWGCraft.

**Comment by twistedatrocity** [comment]
After fixing #16 I cannot replicate this behavior.
