### ISSUE TITLE
Add option to select the weighting used by Schematics Viewer

### ISSUE THREAD

**Issue by Milikilawat** [twistedatrocity/SWGAide-NGE#15]
Add an option that allows users to choose a different weighting from the default one that the Schematics Viewer currently uses.
For example, in Schematics Viewer most chef schematics use the weighting for nutrition as default to determine if a particular resource is fair, good, or great. I would like to be able to check the quality of a resource based on any other weighting it holds in a quality dependant schematic. So for chef resources that would be the weightings for nutrition, duration or flavour; for some beastmaster resources, it would be purity and mutation; for harvester schematics, it would be BER or hopper size, and so on.
Currently, I go to the Schematics tab, select a schematic in The Laboratory and check how a resource performs for any other weightings that can impact the qualities of the finished product. This shows that SWGAide is already measuring a resource based on any of several weightings, hopefully, this means that it won't be too difficult to tie that code to a selection option in the Schematics Viewer.

**Comment by twistedatrocity** [comment]
The schematics viewer is already supposed to do this actually. It could be that the other weightings are not matching the filter for "great/good/fair" to show up in the list, as every time I have looked into this it's always been correctly listing them....

**Comment by twistedatrocity** [comment]
I found this to be a bug. I have it fixed in dev and will be included in the next release.

**Comment by twistedatrocity** [comment]
Fixed in v0.1.25
