### ISSUE TITLE
Exception when trying to open context menu in the inventory tab

### ISSUE THREAD

**Issue by trostboot** [twistedatrocity/SWGAide-NGE#19]
When right-clicking on empty space in the inventory tab, nothing happens.
When right-clicking on a resource already added to the inventory, a silent exception is thrown.
Works fine in other tabs
Log file entry: [SWGAide-ERROR.TXT](https://github.com/twistedatrocity/SWGAide-NGE/files/3720835/SWGAide-ERROR.TXT)
JRE 1.8.0_221-b11, Win10 1903

Happy to provide any other info you might need.

**Comment by twistedatrocity** [comment]
The error log unfortunately gives no clues, it just ran into a null value somewhere. It sounds like maybe your dat file is corrupt. Have you tried setting it up clean in a different directory and see if issue persists? You can do this without deleting your current directory... if it works you can export from the corrupt and import to the clean and go from there I think, might be quickest way to resolve it.

Or if it just started on a certain day you can look in your swgaide directory for a backups directory and pull an older .dat file from there into the working directory and rename it to swgaide.dat (delete the old one first)... then fire it up.

**Comment by trostboot** [comment]
Looks like it was indeed a corrupt file. It was a fresh install to begin with, so not sure what went wrong there, but it's working now. Thank you.
