### ISSUE TITLE
Delete Temporary Characters, not just "Hide" them

### ISSUE THREAD

**Issue by Krtz-Legends** [twistedatrocity/SWGAide-NGE#20]
I have a rotating deletable character that I use to make space collection schematics, and when I go to assign an owner to a resource in inventory the list is about 40 characters or so long. If there was a way to permanently delete characters or accounts that would be great.

**Comment by twistedatrocity** [comment]
After looking into this a bit, aide already has a routine upon every startup that scans for new characters and removes any old ones. However for the removal to happen it has to meet several criteria:
1. The character must not exist in SWG anymore, and any mail folders for that user must be removed from the SWG game profile area e.g.  <SWG>/profiles/<username>/Omega/mail_<character_to_delete>
2. The character must not have any mail folders in the swgaide directory:  <SWGAide>/mails/Omega/<character_to_delete>

I have tested this in my dev environment and it did remove my test characters after completely removing it's mail directories from both the SWG game profile area and aides mails folders.... it did take a couple restarts of the aide app, but it did remove them automatically.

Let me know if doing this works for you.

**Comment by twistedatrocity** [comment]
This was added in Release 0.1.24
closing
