### ISSUE TITLE
add option for laboratory experimentation line toggle or hide

### ISSUE THREAD

**Issue by glypheSWG** [twistedatrocity/SWGAide-NGE#21]
Requested by Glyphe

Add option to hide or toggle on/off unneeded/unwanted experimentation lines for selected schematics in the laboratory tab, possibly as part of the current right-click context menu. Alternatively, create some way of permanently ranking or sticking preferred experimentation lines to the top of the panel.

This is wanted so that we can focus on just the experimentation lines we need to without all the others clogging up the panel and making us scroll way down to hunt for what we want for each resource. Example is for a chef wanting to block out all flavor and quantity lines/resources to show just nutritional value resources. This is especially useful if the crafter is showing more than a few resources per line.
![screenshot_002473](https://user-images.githubusercontent.com/60822219/74089124-fde7bb80-4a6b-11ea-9902-9d308f7ebdb0.jpg)
![screenshot_002474](https://user-images.githubusercontent.com/60822219/74089125-fde7bb80-4a6b-11ea-81be-b35eb8007a53.jpg)

**Comment by twistedatrocity** [comment]
Feature was added to 1.0.5, see tagged screenshot in discord.
