### ISSUE TITLE
application doesn't recognize jre from openjdk

### ISSUE THREAD

**Issue by nekotome** [twistedatrocity/SWGAide-NGE#27]
I am running adopt openjdk with hotspot and have never installed swgaide before.  Every time I try to run the executable it says I need to install the 1.8 JRE.  Adopt already comes with the JRE, I have verified my home variables are set.  This is what I program in at work actually.  Before asking, I am able to run several other java applications from other developers, I suspect it's just trying to detect the oracle specific version instead of simply any java jre/jdk.

java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

javac -version
javac 1.8.0_292

**Comment by twistedatrocity** [comment]
The exe is just a wrapper around the jar made by Launch4j, I have no idea what they check specifically as I've only set a version number in it and "any jre" They must not recognize the builds you are using.

The JAR file may work better for you, instead of the exe. The only difference is some optimization flags in the exe for garbage collection, you can play with those on your own with the jar. Otherwise it needs no flags to run.

**Comment by nekotome** [comment]
I grabbed the bat file from inside the jar and ran it with those params, I assume that is what you are using to test it
"java -jar -Xms50m -Xmx750m SWGAide-Unity.jar"
That executes but it seems the application still needs to run as admin? that might need to be included in the instructions or I am blind before my morning caffeine.  Executing as admin does solve the elevated issue and the program runs normally.

Error testing administrative elevation:
java.lang.NullPointerException
OS: Windows 10
See Windows/Admin section in SWGAide_README.txt
If you continue SWGAide may crash or misbehave

Exit?
Error testing administrative elevation:
java.lang.NullPointerException
OS: Windows 10
See Windows/Admin section in SWGAide_README.txt
If you continue SWGAide may crash or misbehave

Exit?

**Comment by nekotome** [comment]
Going to close, feel free to reopen if you feel the wrapper issue can be resolved.
