### ISSUE TITLE
Avast is blocking the .exe

### ISSUE THREAD

**Issue by HydroTek** [twistedatrocity/SWGAide-NGE#4]
Avast is blocking the .exe, will look into it more when I get home tonight.  Glad to see Zimoons old helper program getting new updates

**Comment by HydroTek** [comment]
Avast popped a window stating it was investigating the .exe
When I tried again after work, Avast popped a window and said something to the effect, that the file was OK ...lol
obviously was getting a false positive, but Avast didnt give a way around the block this morning.  gotta love anti virus programs

**Comment by HydroTek** [comment]
oh forgot to mention the .exe worked fine v1.4

**Comment by HydroTek** [comment]
downloaded v0.1.5 and avast is still blocking ...maybe because publisher field is blank? in file properties

**Comment by twistedatrocity** [comment]
Supposedly Avast has whitelisted it as I'd contacted them some time ago about the false positive. I also built the latest 0.1.5 with an older launch4j that does not cause false positives.

If it's still blocking on you then apparently nothing I did worked to alleviate the issue...   other AV's don't seem to be bothered by it however. 

Will keep looking for a resolution.

**Comment by twistedatrocity** [comment]
Going to close this as I have not heard of any more issues. If it happens again reopen, or submit to avast to have them whitelist it in their cloud.

**Comment by HydroTek** [comment]
Avast temporarily blocks each time Aide is updated. Not sure what is needed
to get white listed. Not a super problem, but takes about an hour before
avast returns an ok

On Mar 16, 2018 9:47 PM, "twistedatrocity" <notifications@github.com> wrote:

Going to close this as I have not heard of any more issues. If it happens
again reopen, or submit to avast to have them whitelist it in their cloud.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/twistedatrocity/SWGAide-NGE/issues/4#issuecomment-373885500>,
or mute the thread

**Comment by twistedatrocity** [comment]
There are two old references to folks having the same issue on other apps:
* https://stackoverflow.com/questions/34592100/launch4j-compiled-java-application-executable-being-blocked-by-antivirus
* https://sourceforge.net/p/launch4j/discussion/332683/thread/d5baedac/#6abf

I had downgraded my launch4j (which is what builds the exe wrapper) to 3.5 thinking this had cured it. Apparently now using 3.5 does not help if it's still flagging on you.

I'm not sure what can be done either, the wrapper is just a simple java launcher, checks java version installed and launches with the one it wants, also asks for elevated perms which is nothing new or abnormal in windows land.
